### ISSUE TITLE
[Feat] Navbar 설정

### ISSUE THREAD

**Issue by 42sungwook** [42SeoulCoalitionhackthon2023/pear42-Frontend#2]
## Detail
Navbar 설정
## ToDo
- [x] _app 페이지 설정
- [x] Navbar 컴포넌트 제작
- [x] Searchbar 컴포넌트 제작
